# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tf_environment: ${var.tenancy}
    tf_gitlab_backup_bucket_name: ${var.region}
    tf_path: ${path.module}
    DOC
  #filename = "../../${path.module}/ansible/inventory/dev/host_vars/tf_ansible_vars_file.yml"
  filename = "${path.module}/tf_ansible_vars_file.yml"
}

